
spring:
  datasource:
    url: jdbc:postgresql://localhost:5450/currency_dev
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false

  cache:
    type: redis


cache:
  config:
    entryTtl: 120
    currencies:
      entryTtl: 120

server:
  port: 8787

currency:
  url: "https://www.yapikredi.com.tr/yatirimci-kosesi/doviz-bilgileri"

jwt:
  key: GWjtA5DqSZ4dwrLcy7gvTruNxbgca3OiWsAxIhiQn2c3yDMV6TO5zQvEtMqyt5nfxqdSPQURXSD63bYCqXpbqYe8EPkiFDsL4EjntqKAZouJIG/qQNvQg+R+O6JJqyseUh6OF9UmNmxeALmAP39yzoUieiuANGCYboiRc3DcgUc=