version: '3.8'

services:
  postgresql:
    image: postgres
    container_name: postgres_currency
    restart: always
    environment:
      POSTGRES_DB: currency_dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5450:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data


  redis:
    image: redis
    ports:
      - "6379:6379"